import type { NextPage } from "next";
import Head from "next/head";
import { useAuthState } from "react-firebase-hooks/auth";
import NavBar from "../components/NavBar";
import MainContent from "../components/MainContent";
import RightMenu from "../components/RightMenu";
import LeftMenu from "../components/LeftMenu";
import PostForm from "../components/PostForm";
import NotUserMenu from "../components/NotUserMenu";
import { auth } from "../firebase/firebase";


const Home: NextPage = () => {
  const [user] = useAuthState(auth);
  return (
    <div>
      <Head>
        <title>nextjs-typescript-tailwindcss-firebase boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.jonchristie.net/favicon.png"
        />
      </Head>
      <NavBar />
      <section className="flex justify-center h-screen">
        <RightMenu />
        <div className="w-full lg:w-2/3 xl:w-2/5 pt-32 lg:pt-16 px-2">
          {user && (
            <>
              <MainContent />
              <PostForm />
            </>
          )}
        </div>
        {user ? <LeftMenu /> : <NotUserMenu />}
      </section>
    </div>
  );
};

export default Home;
